#!/bin/bash
set -e

# Run module generator if Intel oneAPI is installed
if [ -f /opt/intel/oneapi/modulefiles-setup.sh ]; then
    /opt/ohpc/admin/ohpc/bin/ohpc-update-modules-intel || true
fi

#DEBHELPER#

exit 0
