FROM quay.io/almalinuxorg/almalinux:10 AS openeuler-rootfs

ARG OE_MIRROR=https://repo.huaweicloud.com/openeuler/openEuler-24.03-LTS
ARG OE_BASEARCH=ppc64le

RUN mkdir -p /oe-rootfs/etc/yum.repos.d /oe-rootfs/etc/dnf/vars && \
    printf '24.03\n' > /oe-rootfs/etc/dnf/vars/releasever && \
    printf '[openEuler-OS]\nname=openEuler 24.03 LTS OS\nbaseurl=%s/OS/%s/\nenabled=1\ngpgcheck=0\n' \
        "${OE_MIRROR}" "${OE_BASEARCH}" > /oe-rootfs/etc/yum.repos.d/openEuler.repo && \
    dnf -y --installroot=/oe-rootfs \
        --releasever=24.03 \
        --nogpgcheck \
        --setopt=install_weak_deps=False \
        --setopt=reposdir=/oe-rootfs/etc/yum.repos.d \
        install openEuler-release bash coreutils dnf ca-certificates && \
    dnf -y --installroot=/oe-rootfs \
        --releasever=24.03 \
        --setopt=reposdir=/oe-rootfs/etc/yum.repos.d \
        clean all && \
    rm -rf /oe-rootfs/var/cache/dnf/*

FROM scratch
COPY --from=openeuler-rootfs /oe-rootfs /

# Native POWER build container for openEuler 24.03 ppc64le validation. Build
# this image on a ppc64le host; openEuler 24.03 ppc64le has a thin OS
# repository and no official ppc64le Docker base image, so this container
# bootstraps from the native ppc64le RPM repository and rebuilds several support
# packages from openEuler SRPMs.

RUN test "$(uname -m)" = "ppc64le"

ARG OE_MIRROR=https://repo.huaweicloud.com/openeuler/openEuler-24.03-LTS
ARG OE_BASEARCH=ppc64le
RUN mkdir -p /etc/dnf/vars && \
    printf '24.03\n' > /etc/dnf/vars/releasever && \
    printf '[openEuler-OS]\nname=openEuler 24.03 LTS OS\nbaseurl=%s/OS/%s/\nenabled=1\ngpgcheck=0\n' \
        "${OE_MIRROR}" "${OE_BASEARCH}" > /etc/yum.repos.d/openEuler.repo && \
    printf '\nbest=False\n' >> /etc/dnf/dnf.conf

RUN dnf -y install \
        rpm-build dnf-plugins-core createrepo_c \
        gcc gcc-c++ gcc-gfortran make autoconf automake libtool cmake \
        bison flex patch file which hostname git wget curl chrpath \
        python3 python3-devel python3-setuptools python3-pip python3-packaging \
        lua perl perl-devel perl-Encode-devel \
        tcl tcl-devel tk tk-devel vala \
        bzip2 bzip2-devel xz xz-devel zstd zlib-devel \
        openssl-devel ncurses-devel readline-devel \
        libxml2-devel libxslt-devel libcurl-devel expat-devel \
        pam-devel numactl-devel libevent-devel \
        openldap-devel krb5-devel systemd-devel util-linux-devel \
        rdma-core-devel binutils-devel \
        json-c json-glib jsoncpp \
        libicu-devel pcre2-devel libpng-devel \
        fontconfig-devel freetype-devel \
        libX11-devel libXt-devel libXft-devel libXext-devel \
        libXrender-devel libXau-devel libxcb-devel libICE-devel libSM-devel \
        cairo cairo-gobject glib2-devel \
        libffi-devel libstdc++-devel libquadmath-devel \
        libnl3-devel libpq-devel mariadb-connector-c-devel \
        check-devel systemtap-sdt-devel gettext-devel \
    && dnf clean all

ARG GO_VERSION=1.24.0
RUN cd /tmp && \
    wget -q https://go.dev/dl/go${GO_VERSION}.linux-ppc64le.tar.gz && \
    rm -rf /usr/local/go && \
    tar -C /usr/local -xzf go${GO_VERSION}.linux-ppc64le.tar.gz && \
    ln -sf /usr/local/go/bin/go /usr/local/bin/go && \
    /usr/local/go/bin/go version && \
    rm -f go${GO_VERSION}.linux-ppc64le.tar.gz

ARG OE_SRC=${OE_MIRROR}/source/Packages

RUN set -e; \
    cd /tmp; \
    srpm=lua-5.4.6-1.oe2403.src.rpm; \
    wget -q "${OE_SRC}/${srpm}"; \
    rpmbuild --rebuild --nodeps "${srpm}"; \
    rm -f "${srpm}"; \
    dnf -y install \
        /root/rpmbuild/RPMS/ppc64le/lua-5*.rpm \
        /root/rpmbuild/RPMS/ppc64le/lua-devel-*.rpm; \
    for srpm in \
        lua-filesystem-1.8.0-1.oe2403.src.rpm \
        lua-posix-36.1-1.oe2403.src.rpm \
        libfabric-1.20.0-1.oe2403.src.rpm \
        freeipmi-1.6.11-1.oe2403.src.rpm \
        libedit-3.1-31.oe2403.src.rpm \
        yaml-cpp-0.7.0-2.oe2403.src.rpm \
        libyaml-0.2.5-6.oe2403.src.rpm \
        libtirpc-1.3.4-2.oe2403.src.rpm \
        flex-2.6.4-5.oe2403.src.rpm \
        patchelf-0.16.0-1.oe2403.src.rpm \
        opensm-3.3.24-1.oe2403.src.rpm \
        sysfsutils-2.1.1-3.oe2403.src.rpm; do \
            wget -q "${OE_SRC}/${srpm}"; \
            rpmbuild --rebuild --nodeps "${srpm}"; \
            rm -f "${srpm}"; \
        done; \
    dnf -y install \
        /root/rpmbuild/RPMS/ppc64le/lua-filesystem-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/lua-posix-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/libfabric-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/freeipmi-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/libedit-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/yaml-cpp-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/libyaml-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/libtirpc-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/flex-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/patchelf-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/opensm-*.rpm \
        /root/rpmbuild/RPMS/ppc64le/sysfsutils-*.rpm \
        /root/rpmbuild/RPMS/noarch/flex-help-*.rpm; \
    dnf clean all

RUN useradd -m ohpc || true && \
    mkdir -p /home/ohpc/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} && \
    chown -R ohpc:ohpc /home/ohpc/rpmbuild

COPY components/OHPC_macros /home/ohpc/rpmbuild/SOURCES/OHPC_macros

USER ohpc
WORKDIR /workspace

CMD ["/bin/bash"]
