FROM registry.access.redhat.com/ubi10:latest

RUN dnf -y install yum-utils git rpm-build rpmdevtools dnf-plugins-core \
    curl python3 python3-pip python3-rpm python3-requests jq && \
    pip3 install specfile
